### ISSUE TITLE
Kinetic Release

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit#18]
Discussion moved from old repo: https://github.com/ros-planning/moveit_ros/issues/695

Discuss here issues related to releasing Kinetic. We can track remaining issues in this new milestone: https://github.com/ros-planning/moveit/milestone/1

I don't think we can add milestones for issues in other repos. Creating that list here:
- [x] Cleanup extra [rosinstall instructions](https://github.com/ros-planning/moveit_docs/blob/kinetic-devel/moveit.rosinstall)
- [x] https://github.com/flexible-collision-library/fcl/issues/137
- [x] #63 (changes ABI)
- [x] #187 (addresses unintuitive behavior of the new author feature in msa) --> #221 
- [x] #221 (continuation of #187)
- [x] C++11ifying the public API for the kinetic release #48
- [x] SRDFDom https://github.com/ros-planning/srdfdom/issues/23
- [x] Fix https://github.com/ros-planning/moveit/pull/209
- [x] Plannerarena benchmarking https://github.com/ros-planning/moveit/pull/228
- [x] ~~fix race conditions when updating PlanningScene https://github.com/ros-planning/moveit/pull/232~~ POSTPONED
- [x] moveit_kinematics https://github.com/ros-planning/moveit/pull/247
- [x] Remove manipulation_msgs dependency #282 --> We won't wait for this for initial release
- [x] forward c++11 settings to downstream projects #289
- [x] ~~sonames for libraries #273~~ POSTPONED
- [x] issues with traj validation #283, ~~temporary disable feature https://github.com/ros-planning/moveit/pull/287~~ / resolved in #292
- [x] libfcl-dev on Fedora https://github.com/ros-planning/moveit/issues/18#issuecomment-254749486 --> Can be ignored by bloom https://github.com/ros-planning/moveit/issues/18#issuecomment-254998229
- [x] Release geometric_shapes https://github.com/ros-planning/geometric_shapes/issues/61
- [x] urdfdom for Wily #317
- [x] <s>urdfdom cleanup</s> https://github.com/ros-planning/moveit/pull/319 --> Merge postponed https://github.com/ros-planning/moveit/pull/319#issuecomment-257323621

**Comment by davetcoleman** [comment]
I think we are nearing a beta version of the Kinetic release to bloom. The last thing I'd personally like to see before releasing is a switch to C++11 shared_ptrs in the public header, which is in progress at https://github.com/ros-planning/moveit/issues/48 thanks to @de-vri-es

Is there anything else we need to wait for? Even when we release Kinetic I think we should not consider it "stable" / worry about ABI for a while longer

**Comment by v4hn** [comment]
On Fri, Aug 26, 2016 at 10:24:36AM -0700, Dave Coleman wrote:
> Is there anything else we need to wait for?

I'm not sure right now.

I believe I would like to see https://github.com/ros-planning/moveit/issues/80 resolved
to settle open issues in the message API for kinetic. I have one other change to the `Grasp`
message that I would like to see in kinetic, but I didn't get around to provide a MoveIt patch for it yet...

I know `moveit_msgs` is already released, but we could surely change things before releasing MoveIt itself.
Btw: what was the reason for already releasing the messages? I suppose you did that @130s?

> Even when we release Kinetic I think we should not consider it "stable" / worry about ABI for a while longer

+1

**Comment by 130s** [comment]
> what was the reason for already releasing the messages?

To make a release of a package there should be debs of all dependent packages already available, and generating debs in shadow repo for the first takes certain amount of time (usually 3+ days?). Once it's released, the successive release takes less time for debs to be built. Since I thought `moveit_msgs` and other packages that are depended by packages in `moveit` repo are more stable, I wanted to have them released so that once we want to make a release of moveit we won't have to wait for dependent packages.

Also, I think I've already made multiple version up release of `moveit_msgs`. Reason is because every time new release into other distros (IJ) it's so easier to make a release into K as well to simply not forget to release...Not smart though.

**Comment by davetcoleman** [comment]
> I know `moveit_msgs` is already released, but we could surely change things before releasing MoveIt itself.

For sure. But we should move quick on this.

**Comment by VictorLamoine** [comment]
Do you know when all MoveIt packages will be released for Kinetic?

**Comment by davetcoleman** [comment]
I've just updated the top comment (above) with the remaining blockers for Kinetic. I think we should close those issues ASAP and get kinetic out - its been 4 months since ROS Kinetic was released so I know we need to get it moving! A rough estimation based: 1 month

**Comment by VictorLamoine** [comment]
Thank you for the update, don't hesitate to ask me if you require external testers.

**Comment by davetcoleman** [comment]
You're welcome to use/test the kinetic branch from source now :)

**Comment by arpit15** [comment]
@VictorLamoine were you able to catkin_make the kinetic version. 
My make is failing and giving errors of "conflicting declaration" with geometric_shapes and srdf

**Comment by v4hn** [comment]
On Wed, Sep 28, 2016 at 01:11:17PM -0700, Arpit Agarwal wrote:
> @VictorLamoine were you able to catkin_make the kinetic version.
> My make is failing and giving errors of "conflicting declaration" with geometric_shapes and srdf

Please follow the instructions on http://moveit.ros.org/install/source/
You need to checkout and build geometric_shapes and srdfdom too at the moment.

**Comment by 130s** [comment]
> You need to checkout and build geometric_shapes and srdfdom too at the moment.

Maybe a bit hacky but if you're familiar with how to use [shadow repository](http://wiki.ros.org/ShadowRepository), those 2 pkgs are already available from there so that you don't need to build from source.

If anyone has more questions about source build, I suggest to open a new issue -- this ticket should be saved for release task discussion :)

**Comment by 130s** [comment]
Sorry if I missed anything but what about https://github.com/ros-interactive-manipulation/manipulation_msgs/issues/9

**Comment by v4hn** [comment]
On Sun, Oct 09, 2016 at 03:12:43AM -0700, Isaac I.Y. Saito wrote:
> Sorry if I missed anything but what about https://github.com/ros-interactive-manipulation/manipulation_msgs/issues/9

This has been partially resolved in https://github.com/ros-planning/moveit_msgs/pull/32
and https://github.com/ros-planning/moveit/pull/264 .

If the dependency on `manipulation_msgs` should be avoided from the first kinetic release (+1), either

- the additional glue-code that calls the service in this function could be removed entirely: https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.cpp#L417
  With #264 in the public interface, this becomes *somewhat* redundant.
  However, it would change the logic of the pick action: if no grasps are specified, it would no longer call the service, but instead *only* try the default grasp(s) that are hardcoded.
  It's worth it though in my opinion.

or

- most of the glue-code can be simplified and the interface can be changed to https://github.com/ros-planning/moveit_msgs/pull/32 . This would still leave the problem I explained in #246 though.

Both options are easy to do. I could probably do this earliest the week after next though.

**Comment by v4hn** [comment]
I just added #273 to the check list, which should allow us to change ABIs within ROS distributions in the future without having to tell the whole user-base to recompile their code.

**Comment by v4hn** [comment]
Notice that the main reason I consider #232 to block the kinetic-devel release is that it is ABI incompatible. It depends on the outcome of #273 whether this will remain a problem or not.

**Comment by davetcoleman** [comment]
Its not clear to me what @130s and @v4hn are discussing here regarding manipulation_msgs due to an over-use of links to other issues. You want to entirely remove the dependency on manipulation_msgs from the kinetic release of MoveIt!? Perhaps we can move this conversation to a dedicated issue thread?

**Comment by davetcoleman** [comment]
I would really like to release kinetic in time for our Community Meeting. Thoughts on the various blockers:

- https://github.com/ros-planning/moveit/issues/283 @v4hn reports the PR2 is broken because of the new start state validation feature. We should do a quick and dirty disable of this feature using a ``if (false)`` but leave the logic in there for ABI purposes. In the next Kinetic release we will hopefully have a proper fix. @rhaschke do you mind disabling the feature temporarily?
- https://github.com/ros-planning/moveit/pull/232 - looks like this is ready to merge (minus a tiny [style change](https://github.com/ros-planning/moveit/pull/232#discussion_r82176905)). @Jntzko reported an issue when testing this, but it was related to the start state validation feature #283, which I am proposing we temporarily disable
- https://github.com/ros-planning/moveit/pull/273 - everyone is happy with adding SONAMES, @v4hn just needs to finish applying the change to all moveit packages in this repo.

Its been almost 5 months since the ROS Kinetic release, we are behind! "The enemy of success is perfection"

**Comment by rhaschke** [comment]
Regarding #283: I don't mind to disable the feature. I could also introduce a normalization of revolute joints there. Is the information about revolute joints available there?

**Comment by davetcoleman** [comment]
>  I could also introduce a normalization of revolute joints there.

Certainly we want that also, but I just think we should hold off until the next release for actually enabling this feature to avoid further delays.

**Comment by mahmoudabdulazim** [comment]
Hello, how much time as a rough estimate remains before ROS Kinetic moveit package release?

**Comment by davetcoleman** [comment]
@mahmoudabdulazim I realize there are many ROS users holding back from upgrading to Kinetic because of MoveIt! (which is sad), and we are working hard to finish releasing it. I would like to see it released by the Oct 27th community meeting. Because there will likely be unforeseen release issues, we should ideally start releasing it this week.

To speed up the release, I propose we temporarily disable a new feature that is still buggy: https://github.com/ros-planning/moveit/pull/287/

I also think we should hold back https://github.com/ros-planning/moveit/pull/232 until right after our first Kinetic release, so we have plenty of time to test it and we don't release a buggy new feature.

Therefore, the only blocker for Kinetic remaining is https://github.com/ros-planning/moveit/pull/273

**Comment by 130s** [comment]
Assuming we want to have binary of initial release version of MoveIt! on Kinetic by the community meeting on 10/27, I propose day-by-day schedule from now on (in Pacific time). :

10/27 MCM (MoveIt! Community Meeting)
10/24 Very last call for the release request (note-2)
10/19 Last day to make initial release request (note-1)
10/17 Today

note-1...Initial release takes longer to build on ROS buildfarm. Combined with the software size, I'd say we want to save 5 days for building initial release version. By making a release on 19th, hopefully the binary will be ready on shadow repo by 24th.

note-2...Again with the size of the software released from `moveit` repo, I'd say we want 3 days for it to be built and become available on shadow repo. Making a release on 24th hopefully makes the binary ready by 27th.

With this strict timeframe I think there's little chance that MoveIt! makes it to the official repo by MCM.

**Comment by jiapd** [comment]
Good luck! : )

**Comment by davetcoleman** [comment]
Thank you @130s for the timeline summary.

I believe if we just postpone this questionable feature https://github.com/ros-planning/moveit/pull/287 we are ready for the release - I've been trying hard, with the help of many others, to get this out the door for [4 months](https://github.com/ros-planning/moveit_ros/issues/695) and we must draw the line somewhere. The Community Meeting is an ideal time to draw that line.

I think we should skip the sonames for now since that PR https://github.com/ros-planning/moveit/pull/273 is not ready.

So we just need someone to merge https://github.com/ros-planning/moveit/pull/287 who is not me, the author.

**Comment by davetcoleman** [comment]
After @mikeferguson's [viewpoint](https://github.com/ros-planning/moveit/pull/287#issuecomment-254604963), I've closed #287 in favor of getting new features (possibly buggy) out quickly in our first Kinetic release for testing.

@130s in my opinion we are ready to start releasing Kinetic now.

**Comment by 130s** [comment]
Release not done yet, as there's still an issue (libfcl-dev not available on Fedora? Wait, why Fedora?) after having faced some issues I had to deal with already as expected.

```
$ bloom-release --rosdistro kinetic --track kinetic moveit --edit
:
Pre-verifying RPM dependency keys...
Running 'rosdep update'...
Could not resolve rosdep key 'libfcl-dev' for distro '23':
No definition of [libfcl-dev] for OS [fedora]
        rosdep key : libfcl-dev
        OS name    : fedora
        OS version : 23
        Data: arch:
- fcl
debian:
- libfcl-0.5-dev
ubuntu:
- libfcl-0.5-dev

Failed to resolve libfcl-dev on fedora:23 with: Error running generator: Failed to resolve rosdep key 'libfcl-dev', aborting.
libfcl-dev is depended on by these packages: ['moveit_core', 'moveit_experimental']
<== Failed
Could not resolve rosdep key 'libfcl-dev' for distro '24':
No definition of [libfcl-dev] for OS [fedora]
        rosdep key : libfcl-dev
        OS name    : fedora
        OS version : 24
        Data: arch:
- fcl
debian:
- libfcl-0.5-dev
ubuntu:
- libfcl-0.5-dev

Failed to resolve libfcl-dev on fedora:24 with: Error running generator: Failed to resolve rosdep key 'libfcl-dev', aborting.
libfcl-dev is depended on by these packages: ['moveit_core', 'moveit_experimental']
<== Failed
Some of the dependencies for packages in this repository could not be resolved by rosdep.
You can try to address the issues which appear above and try again if you wish.
Would you like to try again? [Y/n]? n
User aborted after rosdep keys were not resolved.
<== The following generator action reported that it is missing one or more
    rosdep keys, but that the key exists in other platforms:
'['/usr/bin/git-bloom-generate', '-y', 'rosrpm', '--prefix', 'release/kinetic', 'kinetic', '-i', '0']'

If you are absolutely sure that this key is unavailable for the platform in
question, the generator can be skipped and you can proceed with the release.
Skip generator action and continue with release [y/N]? N

<== Error running command '['/usr/bin/git-bloom-generate', '-y', 'rosrpm', '--prefix', 'release/kinetic', 'kinetic', '-i', '0']'
Release failed, exiting.
```

**Already solved (just a record)**
- Turned out both `catkin_prepare_release` and `bloom` hated to see packages with different version in the repository. Because of that I had to add several commits that makes commit history look ugly. Sorry, I at least tried to elaborate the reason why I had to make them in each commit message.
  - At some point in the future I'd like to squash unnecessary commits if it matters, as long as someone can temporarily change the repo setting to allow it.
- `catkin_prepare_release` requires all packages in the repo to be the same version, but seems like it only bumps the packages that are supposed to be released (i.e. those listed in the metapkg's package.xml?).
- Having an issue with `catkin_prepare_release` to bump all packages ([asked](http://answers.ros.org/question/245969/catkin_prepare_release-not-bumping-packages-in-a-certain-folder/)). This time I ended up skipping `catkin_prepare_release` and manually adjusted package versions and created git `tag`.
- #300

**Comment by 130s** [comment]
Either https://github.com/ros-gbp/fcl-release/issues/1 needs resolved, or is there a way to work it around?

**Comment by v4hn** [comment]
@130s maybe I got your timetable wrong, but you wanted to release *today* pacific time.
Isn't that in a couple of hours and not now?

**Comment by 130s** [comment]
@v4hn See https://github.com/ros-planning/moveit/issues/18#issuecomment-254617457, and there was no open checkbox at the top post https://github.com/ros-planning/moveit/issues/18#issue-169441711 before I started making a release and got stumbled upon https://github.com/ros-planning/moveit/issues/18#issuecomment-254745823

**Comment by v4hn** [comment]
> @v4hn See #18 (comment), and there was no open checkbox at the top post #18 (comment) before I started making a release and got stumbled upon #18 (comment)

So does that mean #273 can be part of the release if someone merges it today or not?

**Comment by v4hn** [comment]
I just merged #291 too, I assume this will be part of the release now.

**Comment by davetcoleman** [comment]
> At some point in the future I'd like to squash unnecessary commits if it matters, 

We should never (except extreme circumstances) squash in the main ``*-devel`` branches, especially after other commits have occurred on top of the squash range.

> maybe I got your timetable wrong, but you wanted to release today pacific time.

I think its ideal that @130s has started so we can work out all the release kinks such as the ones he's already encountered. We can release a patch in the next day or two if really necessary.

**Comment by davetcoleman** [comment]
@130s all the final PRs were just merged in. reviewing your progress yesterday it seems like the missing FCL dependency for Fedora is not actually a blocker for releasing to bloom for Ubuntu / Debian, correct?

Can we proceed in releasing?

**Comment by rhaschke** [comment]
> > At some point in the future I'd like to squash unnecessary commits if it matters,

> We should never (except extreme circumstances) squash in the main *-devel branches, especially after other commits have occurred on top of the squash range.

If you would have done your changes on a separate branch first, you would have been able to squash afterwards. Maybe that's an option for the future, allowing to review such release changes via the standard github process?

**Comment by rhaschke** [comment]
@130s I guess, you need to release geometric_shapes first. Otherwise we will face issues due to the recent switch to std::shared_ptr in there.

**Comment by 130s** [comment]
Sorry particularly @v4hn for not being clear about the schedule -- I meant the dates in https://github.com/ros-planning/moveit/issues/18#issuecomment-254368360 were deadlines to make it to MCM. Because I got an earlier go-sign I started working earlier.

Commits succeeded to my work earlier can still be included. In fact, with fcl issue I now worry when the release come through.

> reviewing your progress yesterday it seems like the missing FCL dependency for Fedora is not actually a blocker for releasing to bloom for Ubuntu / Debian, correct?
> Can we proceed in releasing?

Actually it's `bloom` that doesn't move forward with the error. I'll have to ask if there's a way to work around Fedora at least temporarily.

> you need to release geometric_shapes first. Otherwise we will face issues due to the recent switch to std::shared_ptr in there

Got it. I started https://github.com/ros-planning/geometric_shapes/issues/61 but got stuck there too...

**Comment by davetcoleman** [comment]
@tfoote we'd appreciate your help with the missing FCL in Fedora issue

**Comment by 130s** [comment]
@wjwwood said `bloom` should be able to [skip missing rosdep keys for Fedora](http://lists.ros.org/pipermail/ros-release/2015-March/004584.html) so I'm trying again.

**Comment by davetcoleman** [comment]
``bloom``'s prompts about skipping Fedora are confusing, so I tried to clarify them a bit: https://github.com/ros-infrastructure/bloom/pull/407

moveit has been released into kinetic!! :tada: :sparkles: https://github.com/ros/rosdistro/pull/12996

thanks @130s !

now we wait to see if it builds successfully, then we wait for the next ros buildfarm sync

**Comment by 130s** [comment]
:fireworks:  Seems like for [Xenial binary is already ready on shadow-repo](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=moveit).

----

>>>  At some point in the future I'd like to squash unnecessary commits if it matters,
>>
>>    We should never (except extreme circumstances) squash in the main *-devel branches, especially after other commits have occurred on top of the squash range.
>
> If you would have done your changes on a separate branch first, you would have been able to squash afterwards. Maybe that's an option for the future, allowing to review such release changes via the standard github process?

I've never directly committed except for [those approved in maintainer's doc](https://github.com/ros-planning/moveit.ros.org/commit/b44081072ebc001a77ec8f2384f4c2e51441e2b0#diff-38a30cb12d305423c2a737f1fdb41cfcR57), and especially this time as I mentioned I initially tried to rely on `catkin_prepare_release`, which I couldn't handle very well with the current situation at moveit repo.

I also tried to open a PR with squashed commits https://github.com/ros-planning/moveit/pull/308 but it doesn't seem to be easy. So unless there's a demand I stop working on squashing.

**Comment by 130s** [comment]
For `Wily`, building `moveit_core`  seems to be failing.

http://build.ros.org/view/Kbin_uW64/job/Kbin_uW64__moveit_core__ubuntu_wily_amd64__binary/2/console
```
00:04:44 dpkg-checkbuilddeps: Unmet build dependencies: liburdfdom-headers-dev (>= 0.4)
00:04:44 dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
00:04:44 dpkg-buildpackage: warning: (Use -d flag to override.)
00:04:44 E: Building failed
:
00:04:45 Finished: FAILURE
```

While the package in question is listed on rosdep key for Wily, I can't find it listed on http://packages.ubuntu.com. So I [asked on rosdistro](https://github.com/ros/rosdistro/commit/c1774f8ac8745daea697f05825bdf12231d52a46#commitcomment-19516694).

**Comment by tfoote** [comment]
The debian package is requiring liburdfdom-headers-dev (>= 0.4) https://github.com/ros-gbp/moveit-release/blob/debian/kinetic/wily/moveit_core/debian/control#L5

But Wily has 0.3 available. 

```
root@e42efa806512:/# apt-cache search liburdfdom-dev
liburdfdom-dev - URDF DOM - development files
root@e42efa806512:/# apt-cache policy liburdfdom-dev
liburdfdom-dev:
  Installed: (none)
  Candidate: 0.3.0-1build1
  Version table:
     0.3.0-1build1 0
        500 http://archive.ubuntu.com/ubuntu/ wily/universe amd64 Packages
root@e42efa806512:/# apt-cache policy liburdfdom-headers-dev
liburdfdom-headers-dev:
  Installed: (none)
  Candidate: 0.3.0-1
  Version table:
     0.3.0-1 0
        500 http://archive.ubuntu.com/ubuntu/ wily/universe amd64 Packages
```

**Comment by davetcoleman** [comment]
This would sure be easier if the ROS build farm just dropped support for EOL Wily...

**Comment by davetcoleman** [comment]
MoveIt missed the last buildfarm sync because of the version of liburdfdom-dev in Wily as pointed out by @tfoote above. I guess we should revert the changes that required the newer version of liburdfdom-dev, unless someone else has a better idea

**Comment by v4hn** [comment]
Yes, we will need to do that, or support both versions using preprocessor-ifdefs.

**Comment by rhaschke** [comment]
I think, we already have the "ifdefs" in place. Maybe it's only a matter of removing the version in package.xml. I will have a try for this.

**Comment by rhaschke** [comment]
We solved the very same issue in `srdfdom` adding a compatibility header: https://github.com/ros-planning/srdfdom/pull/25. I'm preparing a similar PR for MoveIt.

**Comment by davetcoleman** [comment]
+1

**Comment by tfoote** [comment]
Note that urdfdom 0.3 is also needed on jessie: http://discourse.ros.org/t/urdfdom-headers-inconsistency-for-debian-jessie/737 http://build.ros.org/job/Kbin_djv8_dJv8__moveit_core__debian_jessie_arm64__binary/

**Comment by wjwwood** [comment]
@rhaschke does moveit use `urdfdom` only or does it also use `urdf` (the ROS package)? If it uses `urdf` it would be great to put the compatibility header there, so that it could be used here and in other packages like `rviz`.

**Comment by rhaschke** [comment]
@wjwwood That's a good idea. I will file an appropriate PR.

**Comment by davetcoleman** [comment]
@tfoote just a note, [REP 3: Target Platforms](http://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021) doesn't list Jessie as a required platform for Kinetic (though it references Jessie elsewhere), so I've always been confused about that requirement.

**Comment by wjwwood** [comment]
I do not believe it is required, but like Fedora (rpm) support it is useful to have. Unlike Wily, which I doubt many people are using, and if they are they have an upgrade path in Xenial. For Debian users or Fedora users, switching to Ubuntu to get a binary for a package isn't a very nice option. So Xenial is required, Wily is required but could be dropped completely if some technical issues were resolved, and Jessie is nice to have. So even if we dropped Wily as a required platform, you'd still have to sacrifice the "nice to have" Jessie support in order to just require `urdfdom` 0.4.

If you want to release moveit right now you could revert the changes to use these definitions that are only in 0.4 and add them back in a future release as I did with rviz. Though that might not be so easy to do depending on other dependant changes.

**Comment by davetcoleman** [comment]
@rhaschke has fixed the urdfdom version problem: https://github.com/ros-planning/moveit/pull/317

I believe we are ready for another MoveIt! release

**Comment by 130s** [comment]
Should we wait for #319?

**Comment by davetcoleman** [comment]
No, as explained https://github.com/ros-planning/moveit/pull/319#issuecomment-257323621

**Comment by davetcoleman** [comment]
ping @130s - can we finish up the Kinetic release?

**Comment by 130s** [comment]
Prerelease test for Wily and Xenial passed locally!

**Comment by 130s** [comment]
Prerelease test for Wily and Xenial passed locally!

Just a record for the release maintainance task: This time again I had to mess the commits a little bit (much better than the last time :p) for the following reasons that I'll have to fix for the future release:

- `catkin_generate_changelog` didn't update CHANGELOG.rst files in a lot of packages in the repo. Didn't take note this time though, I feel like there's something for the tool with the large repository like `moveit` where folder/package structure isn't the simplest.
- Following packages(/folders) somehow didn't get their versions incremented in package.xml files by `catkin_prepare_release`. Similar/the same issue with [this question of mine](http://answers.ros.org/question/245969/catkin_prepare_release-not-bumping-packages-in-a-certain-folder/). This time again I manually updated the changelog for these packages, committed and pushed a new tag:
  - moveit_controller_manager_example
  - moveit_fake_controller_manager
  - moveit_plugins
  - moveit_ros_control_interface
  - moveit_simple_controller_manager
  - benchmarks
  - planning_interface
  - warehouse

**Comment by 130s** [comment]
Sorry web browser is getting cranky, have to post multiple times.

----

Prerelease test for Wily and Xenial passed locally!

Just a record for the release maintainance task: This time again I had to mess the commits a little bit (much better than the last time :p) for the following reasons that I'll have to fix for the future release:

- `catkin_generate_changelog` didn't update CHANGELOG.rst files in a lot of packages in the repo. Didn't take note this time though, I feel like there's something for the tool with the large repository like `moveit` where folder/package structure isn't the simplest.
- Following packages(/folders) somehow didn't get their versions incremented in package.xml files by `catkin_prepare_release`. Similar/the same issue with [this question of mine](http://answers.ros.org/question/245969/catkin_prepare_release-not-bumping-packages-in-a-certain-folder/). This time again I manually updated the changelog for these packages, committed and pushed a new tag:
  - moveit_controller_manager_example
  - moveit_fake_controller_manager
  - moveit_plugins
  - moveit_ros_control_interface
  - moveit_simple_controller_manager
  - benchmarks
  - planning_interface
  - warehouse
- `bloom` complains that there were packages with different versions in the repo, which I manually adjusted by incrementing the versions that are smaller to higher (0.9.1 to 0.9.2 this time).
- `bloom-release` also warns many times that there are packages from this repo that are not listed on rosdistro, e.g. `chomp*`. I didn't see this for the last time release into Kinetic, so I might have done something wrong. bloom allows to skip those so that we can still make a release without releasing those we don't want to release.

**Comment by davetcoleman** [comment]
rosdistro: https://github.com/ros/rosdistro/pull/13138

**Comment by davetcoleman** [comment]
@tfoote the [buildfarm](http://build.ros.org/view/Ksrc_uX/job/Ksrc_uX__moveit_core__ubuntu_xenial__source/) says "This job has been disabled by 'Disable Failed Job Plugin' due to consecutive failures. This project is currently disabled" but now that we've fixed Wily I think it needs re-enabling.

**Comment by 130s** [comment]
Not sure what is https://github.com/ros/rosdistro/pull/13139 but I'll look into it.

**Comment by tfoote** [comment]
@130s The bloom process only generated a fraction of the tags necessary. It seemed to run the first stage for generic release tags, but not generate any of the platform specific tags.

**Comment by 130s** [comment]
@tfoote Sorry but I haven't fully understood the problem yet. Was it just during the last bloom run something went wrong that can be fixed by the new bloom run? Or is there something that needs to be fixed before/after the new bloom run?

**Comment by tfoote** [comment]
Not all the tags and branches were created by the last bloom run. A rerun watching the console output carefully for errors will either reveal the problem or hopefully just fix it. Likely one of the push steps failed. So I'd suggest trying bloom again and make sure to retain the logs and console output in case there's still a problem.

**Comment by davetcoleman** [comment]
Now that https://github.com/ros-planning/moveit/issues/357 should be addressed, we're ready to try releasing Kinetic again

**Comment by 130s** [comment]
Prerelease test for Xenial failed. I'll need to look deeper but I assume this will be fixed once the newest `moveit_msgs` binary becomes available?
```
generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml   kinetic default ubuntu xenial amd64   moveit   --level 0   --output-dir ./
:
[ 55%] Built target object_recognition_msgs_generate_messages_cpp
Scanning dependencies of target moveit_move_group_interface
[ 61%] Building CXX object move_group_interface/CMakeFiles/moveit_move_group_interface.dir/src/move_group_interface.cpp.o
/tmp/catkin_workspace/src/moveit/moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp:60:39: fatal error: moveit_msgs/GraspPlanning.h: No such file or directory
compilation terminated.
move_group_interface/CMakeFiles/moveit_move_group_interface.dir/build.make:62: recipe for target 'move_group_interface/CMakeFiles/moveit_move_group_interface.dir/src/move_group_interface.cpp.o' failed
make[2]: *** [move_group_interface/CMakeFiles/moveit_move_group_interface.dir/src/move_group_interface.cpp.o] Error 1
CMakeFiles/Makefile2:3152: recipe for target 'move_group_interface/CMakeFiles/moveit_move_group_interface.dir/all' failed
make[1]: *** [move_group_interface/CMakeFiles/moveit_move_group_interface.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'moveit_ros_planning_interface': 
  Command '['/tmp/catkin_workspace/install_isolated/env.sh', 'make', '-j1']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /tmp/catkin_workspace/build_isolated/moveit_ros_planning_interface && /tmp/catkin_workspace/install_isolated/env.sh make -j1

Command failed, exiting.
# END SUBSECTION
```

**Comment by 130s** [comment]
> Prerelease test for Xenial failed. I'll need to look deeper but I assume this will be fixed once the newest moveit_msgs binary becomes available?

moveit_msgs 0.9.0, which includes https://github.com/ros-planning/moveit_msgs/pull/32, is already released and being built on buildfarm should fix this. We shouldn't even need https://github.com/ros-planning/moveit_msgs/pull/35 to make Kinetic release I suppose.

**Comment by davetcoleman** [comment]
moveit_msgs has finished building on the buildfarm successfully

**Comment by 130s** [comment]
Prerelease test passed for Xenial, but not for Wily. 

If I'm not mistaken something is happening around urdf_headers but no idea why the error only occurs for Wily.

```
$ generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml   kinetic default ubuntu wily amd64   moveit   --level 0   --output-dir ./
./prerelease.sh
:
Scanning dependencies of target test_constraint_samplers
[ 94%] Building CXX object constraint_samplers/CMakeFiles/test_constraint_samplers.dir/test/test_constraint_samplers.cpp.o
[ 96%] Building CXX object constraint_samplers/CMakeFiles/test_constraint_samplers.dir/test/pr2_arm_kinematics_plugin.cpp.o
[ 98%] Building CXX object constraint_samplers/CMakeFiles/test_constraint_samplers.dir/test/pr2_arm_ik.cpp.o
In file included from /tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:39:0:
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.h:170:34: error: ‘urdf::JointConstSharedPtr’ has not been declared
   void addJointToChainInfo(urdf::JointConstSharedPtr joint, moveit_msgs::KinematicSolverInfo &info);
                                  ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp: In member function ‘bool pr2_arm_kinematics::PR2ArmIK::init(const urdf::ModelInterface&, const string&, const string&)’:
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:61:3: error: ‘LinkConstSharedPtr’ is not a member of ‘urdf’
   urdf::LinkConstSharedPtr link = robot_model.getLink(tip_name);
   ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:64:5: error: ‘JointConstSharedPtr’ is not a member of ‘urdf’
     urdf::JointConstSharedPtr joint;
     ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:65:15: error: request for member ‘parent_joint’ in ‘link’, which is of non-class type ‘int(const char*, const char*) throw ()’
     if (link->parent_joint)
               ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:66:7: error: ‘joint’ was not declared in this scope
       joint = robot_model.getJoint(link->parent_joint->name);
       ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:66:42: error: request for member ‘parent_joint’ in ‘link’, which is of non-class type ‘int(const char*, const char*) throw ()’
       joint = robot_model.getJoint(link->parent_joint->name);
                                          ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:67:10: error: ‘joint’ was not declared in this scope
     if (!joint)
          ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:69:17: error: request for member ‘parent_joint’ in ‘link’, which is of non-class type ‘int(const char*, const char*) throw ()’
       if (link->parent_joint)
                 ^
In file included from /tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:38:0:
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:70:52: error: request for member ‘parent_joint’ in ‘link’, which is of non-class type ‘int(const char*, const char*) throw ()’
         logError("Could not find joint: %s", link->parent_joint->name.c_str());
                                                    ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:72:55: error: request for member ‘name’ in ‘link’, which is of non-class type ‘int(const char*, const char*) throw ()’
         logError("Link %s has no parent joint", link->name.c_str());
                                                       ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:75:9: error: ‘joint’ was not declared in this scope
     if (joint->type != urdf::Joint::UNKNOWN && joint->type != urdf::Joint::FIXED)
         ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:77:35: error: request for member ‘parent_joint’ in ‘link’, which is of non-class type ‘int(const char*, const char*) throw ()’
       link_offset.push_back(link->parent_joint->parent_to_joint_origin_transform);
                                   ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:110:33: error: request for member ‘parent_joint’ in ‘link’, which is of non-class type ‘int(const char*, const char*) throw ()’
       addJointToChainInfo(link->parent_joint, solver_info_);
                                 ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:113:38: error: request for member ‘getParent’ in ‘link’, which is of non-class type ‘int(const char*, const char*) throw ()’
     link = robot_model.getLink(link->getParent()->name);
                                      ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp: At global scope:
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:153:42: error: variable or field ‘addJointToChainInfo’ declared void
 void PR2ArmIK::addJointToChainInfo(urdf::JointConstSharedPtr joint, moveit_msgs::KinematicSolverInfo &info)
                                          ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:153:36: error: ‘JointConstSharedPtr’ is not a member of ‘urdf’
 void PR2ArmIK::addJointToChainInfo(urdf::JointConstSharedPtr joint, moveit_msgs::KinematicSolverInfo &info)
                                    ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:153:102: error: expected primary-expression before ‘&’ token
 void PR2ArmIK::addJointToChainInfo(urdf::JointConstSharedPtr joint, moveit_msgs::KinematicSolverInfo &info)
                                                                                                      ^
/tmp/catkin_workspace/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:153:103: error: ‘info’ was not declared in this scope
 void PR2ArmIK::addJointToChainInfo(urdf::JointConstSharedPtr joint, moveit_msgs::KinematicSolverInfo &info)
                                                                                                       ^
constraint_samplers/CMakeFiles/test_constraint_samplers.dir/build.make:100: recipe for target 'constraint_samplers/CMakeFiles/test_constraint_samplers.dir/test/pr2_arm_ik.cpp.o' failed
make[3]: *** [constraint_samplers/CMakeFiles/test_constraint_samplers.dir/test/pr2_arm_ik.cpp.o] Error 1
make[2]: *** [constraint_samplers/CMakeFiles/test_constraint_samplers.dir/all] Error 2
CMakeFiles/Makefile2:4956: recipe for target 'constraint_samplers/CMakeFiles/test_constraint_samplers.dir/all' failed
CMakeFiles/Makefile2:1753: recipe for target 'CMakeFiles/tests.dir/rule' failed
make[1]: *** [CMakeFiles/tests.dir/rule] Error 2
Makefile:862: recipe for target 'tests' failed
make: *** [tests] Error 2
<== Failed to process package 'moveit_core':
  Command '['/tmp/catkin_workspace/devel_isolated/moveit_commander/env.sh', 'make', '-j1', 'tests']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /tmp/catkin_workspace/build_isolated/moveit_core && /tmp/catkin_workspace/devel_isolated/moveit_commander/env.sh make -j1 tests

Command failed, exiting.
# END SUBSECTION
```

**Comment by davetcoleman** [comment]
Whatever docker the pre-release test is using has not been updated for the last ROS buildfarm sync that includes the latest URDFDom headers we need. You might be using an old docker image cached on your computer. Try resetting all containers and images:

    docker rm $(docker ps -a -q)                                                                                       
    docker rmi $(docker images -q)  

Then re-run the prerelease. I'm testing the moveit build on Wily using Docker as we speak...

**Comment by davetcoleman** [comment]
just verified: with the latest ROS Wily Docker moveit passes!

**Comment by davetcoleman** [comment]
Except the tests were still failing, fixed in: https://github.com/ros-planning/moveit/pull/364

**Comment by davetcoleman** [comment]
MoveIt! has fully passed on [the buildfarm](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=moveit) for X64! But we still have some failures in other platforms:

- moveit_planners/moveit_planners_ompl: W32 and X32 - because the OMPL build is failing, see [issue](https://bitbucket.org/ompl/ompl/issues/293/ompl-build-timeout-on-ros-buildfarm)
- moveit_setup_assistant: X32: perhaps a [Docker error](http://build.ros.org/view/Kbin_uX32/job/Kbin_uX32__moveit_setup_assistant__ubuntu_xenial_i386__binary/6/console) that will go away soon? Message: ``Cannot connect to the Docker daemon. Is the docker daemon running on this host?``

**Comment by v4hn** [comment]
On Sun, Nov 20, 2016 at 12:21:05PM -0800, Dave Coleman wrote:
> MoveIt! now fully builds for all Ubuntu platforms on the buildfarm! We're ready for the next sync.

nice!

**Comment by anderwm** [comment]
Out of curiosity, how often does this happen(sync)? I still don't see a ros-kinetic-moveit-full in Ubuntu

**Comment by davetcoleman** [comment]
Seems like about every month, but it largely depends on the build farm. You can track upcoming ones here: http://discourse.ros.org/c/release

No new Kinetic sync has been scheduled yet. If you started a discussion there, I bet it would help move it along.

**Comment by davetcoleman** [comment]
Email announcement sent, blog post is up, and website is updated with install instructions for Kinetic. Closing this issue.
